name: mspr_bloc_4 # Commande qui nomme le conteneur global de l'application

services: # Commande qui liste les  différents services de l'application FutureKawa
# -----------
# BDD métier
# ----------
  db: # image de la BDD
    image: mysql:8.0
    container_name: futurekawa-db
    command: --lower_case_table_names=1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=futurekawa
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./futurekawa.sql:/docker-entrypoint-initdb.d/1_structure.sql
      - ./kawa_seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
    networks:
      - futurekawa

# -----------
# PARTIE API / BACKEND
# ----------
  web: # image du Backend
    build:
      context: ./MSPR1/    # Commande qui pointe vers le dossier de l'API
      dockerfile: Dockerfile
    container_name: futurekawapp
    restart: always
    ports:
      - "5000:5000"
    environment:
    - ./MSPR1/.env
    depends_on:
      - db
    networks:
      - futurekawa

# -----------
# PARTIE FRONTEND
# ----------
  front: # image du Frontend
    build:
      context: ./futureKawaFront   # Commande qui pointe vers le dossier du front
      dockerfile: Dockerfile
    container_name: futurekawa-front
    restart: always
    ports:
      - "9090:4173"
    depends_on:
      - web
    networks:
      - futurekawa

# -----------
# BDD IOT
# ----------
  db_iot:
    container_name: iot_db
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=futureKawa
    ports:
      - "3308:3306"
    volumes:
      - iot_db_data:/var/lib/mysql
      - ./futurekawa/controllers/database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - futurekawa

  mosquitto: # Receptionne les données pour les envoyer vers le Backend de l'ESP-32
    image: eclipse-mosquitto
    container_name: futurekawa-mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./futurekawa/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - futurekawa

# -----------
# BACKEND IOT
# ----------
  flask:  # Backend du micro-contrôleur
    build:
      context: ./futurekawa
      dockerfile: Dockerfile
    container_name: futurekawa-iot_service
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - ./futurekawa/.env
    depends_on:
      db_iot:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      - futurekawa

volumes:
  db_data:
  iot_db_data:

# -----------
# Déclaration du network
# ----------
networks:
  futurekawa:
    driver: bridge